#################################################### GG DEFINITION ####################################################

SIMULATION:

  t_start:  0.0       # Simulation Start Time (s)
  t_stop:   5         # Simulation Stop Time (s)
  dt_fix:   0.05      # Fixed Timestep (s)
  dt_init:  1.0e-6    # Initial Timestep (s)

  max_dp:   0.1e+5   # Maximum Pressure Increment for adaptive timesteping (s)  

  alpha:    0.01       # Low Frequency Damping Parameter (n.d)
    

#################################################### System Sizing ####################################################

SIZING:

  GAS_GENERATOR:
    
    # Combustion Chamber Pressure

    P_cc:             25.0e+5   # Nominal Chamber Pressure (Pa)
    P_init:           1.0e+5    # Initial Chamber Pressure (Pa)

    # Injector Conditions

    P_inj_ox:         50.0e+5   # Nominal Oxidiser Injector Pressure (Pa)
    P_inj_ox_init:    1.0e+5    # Initial Oxidiser Injector Presusre (Pa)
    Cd_o:             0.5       # Oxidiser Injector Discharge Coefficient (n.d)

    P_inj_fu:         50.0e+5   # Nominal Fuel Injector Pressure (Pa)
    P_inj_fu_init:    1.0e+5    # Initial Fuel Injector Presusre (Pa)
    Cd_f:             0.4       # Fuel Injector Discharge Coefficient (n.d)

    # Engine Sizing

    m_dot:            38.655e-3 # Nominal Mass Flow Rate of Engine (kg/s)
    MR:               1         # Nominal Mixture Ratio of Engine (n.d)
    
    # Engine Parameters

    eta_c:            0.85      # C* efficiency of the engine (%)
    L_star:           3         # Characterisitic Length of Engine (m)
    
    # Injector Volumes

    V_ox_inj:         0.5e-3    # Oxidiser Manifold Volume (L)
    V_fu_inj:         0.5e-3    # Fuel Manifold Volume (L)


  #################################################### MAIN ENGINE DEFINITION ####################################################

  MAIN_ENGINE:
    
    # Combustion Chamber Pressure

    P_cc:             30.0e+5   # Nominal Chamber Pressure (Pa)
    P_init:           1.0e+5    # Initial Chamber Pressure (Pa)

    # Injector Conditions

    P_inj_ox:         50.0e+5   # Nominal Oxidiser Injector Pressure (Pa)
    P_inj_ox_init:    1.0e+5    # Initial Oxidiser Injector Presusre (Pa)
    Cd_o:             0.6       # Oxidiser Injector Discharge Coefficient (n.d)

    P_inj_fu:         50.0e+5   # Nominal Fuel Injector Pressure (Pa)
    P_inj_fu_init:    1.0e+5    # Initial Fuel Injector Presusre (Pa)
    Cd_f:             0.6       # Fuel Injector Discharge Coefficient (n.d)

    # Engine Sizing

    m_dot:            50.0e-3   # Nominal Mass Flow Rate of Engine (kg/s)
    MR:               1         # Nominal Mixture Ratio of Engine (n.d)
    
    # Engine Parameters

    eta_c:            0.85      # C* efficiency of the engine (%)
    L_star:           3         # Characterisitic Length of Engine (m)
    
    # Injector Volumes

    V_ox_inj:         0.5e-3    # Oxidiser Manifold Volume (L)
    V_fu_inj:         0.5e-3    # Fuel Manifold Volume (L)



  #################################################### VALVE DEFINITION ####################################################

VALVES:

  GG_MOV:
    Name:         "Gas Generator Main Oxidiser Valve"
    OD:           4.0e-3
    Cd:           0.6
    Tau:          150.0e-3
    s_pos_init:   0

  GG_MFV:
    Name:         "Gas Generator Main Fuel Valve"
    OD:           4.0e-3
    Cd:           0.6
    Tau:          150.0e-3
    s_pos_init:   0

  ME_MOV:
    Name:         "Main Engine Main Oxidiser Valve"
    OD:           4.0e-3
    Cd:           0.6
    Tau:          150.0e-3
    s_pos_init:   0

  ME_MFV:
    Name:         "Main Engine Main Fuel Valve"
    OD:           4.0e-3
    Cd:           0.6
    Tau:          150.0e-3
    s_pos_init:   0


#################################################### Turbopump DEFINITION ####################################################

TURBOPUMPS:

  MERMAID_MAN:
    
    FUEL_PUMP:
      
      type:     "Pump"
      D_1:      14.89e-3    # Impeller Eye Diameter (m)  
      D_2:      54.31e-3    # Impeller Outer Diameter (m)
      D_3:      2.6e-3      # Diffuser Throat Diameter (m)
      C_c:      0.8         # Blockage factor for flow Vena-contra (n.d)
      psi:      1         # Pressure Factor for Pump (proxy of slip factor)
      eta_bep:  0.28        # Best Efficiency Point (%)
      N_bep:    24.0e+3     # Best Efficiency Point Rotational Speed (RPM)

    FUEL_TURBINE:
      
      type:     "Turbine"
      u_co_nom: 0.13        # Turbine Nominal Deflection Angle (Degrees)
      a_rat:    4.11        # Turbine Area Ratio (A_2/A_1)
      D_m:      0.147       # Turbine Mean Diameter (m)
      eta_nom:  0.28        # Turbine Derived Efficiency (%)

    SYSTEM:
      
      N_nom:  24.0e+3       # Turbopump Nominal Rotational Speed (RPM)
      I:      0.00698       # Turbopump Polar Moment of Inertia (kg  m^2)
      N_init: 0.1           # Turbopump Initial Rotational Rate (RPM)

SEQUENCE:
  
  GG_MFV: [[0, 60]]         # Gas Generator Main Fuel Valve Sequence
    
  GG_MOV: [[0, 60]]         # Gas Generator Main Oxidiser Valve Sequence
    
  ME_MFV: [[60, 70]]        # Main Engine Main Fuel Valve Sequence
    
  ME_MOV: [[60, 70]]        # Main Engine Main Oxidiser Valve Sequence



PROPELLANTS:

  Oxidiser:
    
    Name:             "N2O"
    Density:          787       # Propellant Density (kg/m^3)
    Compressibility:  1.5e+9    # Propellant Bulk Modulus (Pa)
    P_deliver:        50.0e+5   # Propellant Delivery Pressure From Test House (Pa)


  Fuel:
  
    Name:             "C3H8O,2propanol"
    Density:          785       # Propellant Density (kg/m^3)
    Compressibility:  9.0e+8    # Propellant Bulk Modulus (Pa)
    P_deliver:        30.0e+5   # Propellant Delivery Pressure From Test House (Pa)